version: '2'

services:
  web:
    build:
      context: ./webapp
    ports:
      - '8080:8080'
    environment:
      - ISUCON5_DB_HOST=mysql
      - ISUCON5_DB_PASSWORD=mysql
    networks:
      - default

  mysql:
    build:
      context: ./mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    networks:
      - default
